### ISSUE TITLE
Doxygen Windows links fails due to TLS issues in SourceForge

### ISSUE THREAD

**Issue by aminya** [aminya/setup-cpp#101]
Reported in the discussions in:
https://community.chocolatey.org/packages/doxygen.install

Reproduction:
https://github.com/aminya/project_options/runs/7365919173?check_suite_focus=true
https://github.com/aminya/project_options/pull/137

**Comment by aminya** [comment]
These links are working again. Seemed like an issue from SourceForge

**Comment by aminya** [comment]
The links are failing again.

**Comment by aminya** [comment]
The links are very flaky. They randomly start failing.

**Comment by Subtixx** [comment]
Is there any plans to get rid of SourceForge? I have a private repository with 3 Windows actions which are all failing randomly.

**Comment by aminya** [comment]
These are the official Doxygen links. The links in https://www.doxygen.nl/download.html redirect to SourceForge. One thing we can do is to ask upstream to fix the issue.

**Comment by aminya** [comment]
We can also add a retry mechanism, in which the downloading is tried multiple times with some delays in between until it is successful.
