### ISSUE TITLE
Add powershell tool

### ISSUE THREAD

**Issue by abeimler** [aminya/setup-cpp#105]
Add [powershell](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.2) for different platforms.
_(For example needed for cross-compiling with vcpkg and `x64-mingw-dynamic` windows triplets, #103)_
_cmake/vcpkg error: Could not find Z_VCPKG_BUILTIN_POWERSHELL_PATH using the following names powershell_

* [ ] Example: `.\setup_cpp_linux --powershell true`
* [ ] Platforms
  * [ ] Windows
     	* use choco if not already exist 
     	* or install via [MSI](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2)
  * [ ] Linux - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2
    * Ubuntu/Debia via [deb](https://docs.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.2) or [Package Repository](https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2)
       * Like this:
         `
curl -sSL https://github.com/PowerShell/PowerShell/releases/download/v7.2.5/powershell-lts_7.2.5-1.deb_amd64.deb -o /tmp/powershell.deb && 
    apt-get update -y && apt-get install -y /tmp/powershell.deb && 
    apt-get clean && rm -rf /var/lib/apt/lists/* && 
    rm /tmp/powershell.deb
         `
  * [ ] Fedora - ???
  * [ ] macOS - https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2
  * [ ] Arch Linux - via AUR [`powershell-bin`](https://aur.archlinux.org/packages/powershell-bin)
* [ ] Versioning ??? - For example [Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2): 7.0, 7.1 or 7.2

**Comment by aminya** [comment]
Added a pull request to fix this #113
