### ISSUE TITLE
Setup LLVM with RTTI

### ISSUE THREAD

**Issue by gavrilikhin-d** [aminya/setup-cpp#122]
Is it possible to setup LLVM with RTTI? 

I always get `undefined reference to 'typeinfo for llvm::cl::GenericOptionValue'` in my workflows.

**Comment by aminya** [comment]
We use the official binaries. How can you set up the runtime information?

**Comment by gavrilikhin-d** [comment]
Add fallback option to build from source, for example

**Comment by aminya** [comment]
Building LLVM from the source requires a lot of resources and hard drive storage. This isn't something that a typical C++ developer needs to do. This warning might be because of your system configuration. I haven't seen this on the systems I have tried.
