### ISSUE TITLE
Cppcheck installation fails on Arch Linux

### ISSUE THREAD

**Issue by aminya** [aminya/setup-cpp#125]
```
error: failed to commit transaction (conflicting files)
   filesystem
```
https://github.com/aminya/setup-cpp/actions/runs/3079799317/jobs/4976437548#step:7:1201

**Comment by abeimler** [comment]
When running `node ./setup_cpp.js --cppcheck true` (on its own), it works.

I test it a bit:
* `node ./setup_cpp.js --cppcheck true`: Works
* `node ./setup_cpp.js --cppcheck true --ccache true`: Works
* `node ./setup_cpp.js --cppcheck true --cmake true`: Works
* `node ./setup_cpp.js --cppcheck true --vcpkg true`: Works
* `node ./setup_cpp.js --cppcheck true --doxygen true`: Works
* `node ./setup_cpp.js --cppcheck true --gcovr true`: Fails
* `node ./setup_cpp.js --compiler llvm --task true`: Works

`gcovr` gets installed via pip and installs `pygments`.
When installing `cppcheck`, `pygments` seems to be installed via pacman.

Installing `python-pygments` before running setup_cpp.js seems to fix it ?, but idk why.
(Maybe it didn't need to be reinstalled when installing `cppcheck` and no conflicts happen)
```docker
RUN pacman -S --noconfirm python-pygments
RUN node ./setup_cpp.js --cppcheck true --gcovr true
```
```docker
RUN pacman -S --noconfirm python-pygments
RUN node ./setup_cpp.js --compiler llvm --cmake true --ninja true --cppcheck true --ccache true --vcpkg true --doxygen true --gcovr true --task true
```
