### ISSUE TITLE
Defaulting to LLVM 15

### ISSUE THREAD

**Issue by aminya** [aminya/setup-cpp#130]
Currently, setup-cpp defaults to LLVM 13 because it is widely supported on several platforms including Ubuntu 18, Ubuntu 20, Ubuntu 22, MacOS 10.15, MacOS 11, MacOS 12, and Windows. 

But we should probably default to LLVM 15 if it doesn't break the C++ integration tests.

**Comment by SK83RJOSH** [comment]
LLVM 14/15 brought in tons of useful features in terms of format checks, new diagnostics, and more or less completed the bulk of C++20 language support. I think it would be a reasonable target to use as the default once platform support is sorted out purely on the basis of allowing people to start using the latest standard. Similarly I believe the default version of GCC could use a small bump, but I've noticed no major issues there. :)

**Comment by SK83RJOSH** [comment]
Just to follow up on this, LLVM-15 probably requires GCC-12 given that GCC-11 lacks a lot of library features (a few constexpr containers is the most notable issue). Unfortunately I see that there's still no way to use GCC-12 though. 😞
