### ISSUE TITLE
Better handling of a the GCC version installed for a LLVM version

### ISSUE THREAD

**Issue by SK83RJOSH** [aminya/setup-cpp#136]
So it turns out LLVM-15 doesn't fully support ranges in libc++, and as a result I've managed to get myself into a bit of a jam again with CI. 😢 

That said, GCC-12 *does* support ranges, and ideally llvm versions >= 15 should install 12 instead of the default 11 as is done [here](https://github.com/aminya/setup-cpp/blob/master/src/llvm/llvm.ts#L305). I would submit a PR for this, but I'm not 100% certain what the best way to go about this should be. Since GCC-12  still isn't available on ubuntu-latest images it doesn't make a whole lot of sense to bump the default version to 12, so perhaps a monkey patch checking for this LLVM version is most ideal?

**Comment by aminya** [comment]
We should probably add a map to choose the default GCC version for a particular LLVM version

```ts
// The GCC version installed for a particular LLVm version
export const GccForLlvm: Record<string, string> = {
  "15": "12",
  "14": "12",
  "13": "11",
  "12": "11",
}
```
