### ISSUE TITLE
Syncing GCOV env and GCC version to prevent empty uploads

### ISSUE THREAD

**Issue by SK83RJOSH** [aminya/setup-cpp#140]
Gcovr's documentation is pretty clear in that you should supply the version of gcov when calling the tool. Either by `set GCOV=gcov-12` or `--gcov-executable gcov-12`, if you don't you run the risk of this happening. This took me a couple of days to figure out unfortunately. Luckily this is configurable in the workflow easily enough, I would just specify gcc-11 and gcov-11 to make it clear the versions are tied together to prevent future users from going down this path. 😄

**Comment by aminya** [comment]
Thanks for the explanation. I merged https://github.com/aminya/cpp_vcpkg_project/pull/18 as the temporary fix.
We should implement the permanent fix here in setup-cpp.

**Comment by Spacetown** [comment]
> I already have a `syncVersion` function used to sync LLVM tools. We can use the same thing for syncing Gcovr and Gcc

You need to sync gcov (no r at the end) and GCC.

**Comment by aminya** [comment]
So, I think we need to add the `GCOV` environment variable based on the GCC version installed.
