### ISSUE TITLE
LLVM LDFLAGS with quotation marks

### ISSUE THREAD

**Issue by lczech** [aminya/setup-cpp#145]
Hi there,

I'm having a weird issue in the interaction of my GitHub Actions CI environment and a C library called [htslib](https://github.com/samtools/htslib).

The htslib `Makefile` defines [some preprocessor values](https://github.com/samtools/htslib/blob/8e43fb0650fabb8ca34775510e1e33ce6e48fc2a/Makefile#L165-L169) using quotation marks such as

    echo '#define HTS_LDFLAGS "$(LDFLAGS)"' >> $@

In my GitHub Actions, I'm using setup-cpp with clang/llvm, which also [uses quotation marks around flags](https://github.com/aminya/setup-cpp/blob/8c9d48b9aa22b181d0ff81b04d3957e19462fb00/src/llvm/llvm.ts#L74-L75) such as

    addEnv("LDFLAGS", `-L"${directory}/lib"`),

which causes the preprocessor value of htslib to become for example

    #define HTS_LDFLAGS "-L"/home/runner/llvm/lib" -fvisibility=hidden "

That of course fails to compile, as the path in there is not part of the quoted string. 

I'm currently working around this by having

    export LDFLAGS=`echo ${LDFLAGS} | sed 's/"//g'`
    export CPPFLAGS=`echo ${CPPFLAGS} | sed 's/"//g'`

in my CI setup, but that does not seam ideal.

Honestly, I'm not entirely sure who is right here. On the one hand, putting a path in quotation marks seems okay on the setup-cpp side. On the other hand, having flags in a quoted string seems necessary from the point of view of htslib. My guess is that htslib should escape quotation marks within the `$(LDFLAGS)` when processing the `Makefile`. I have [opened an issue](https://github.com/samtools/htslib/issues/1527) on their end. 

However, I'm also opening this issue here, as I am not sure that those paths should necessarily be quoted in setup-cpp. 

Cheers and thanks
Lucas

**Comment by feltech** [comment]
Perhaps I'm missing something, since [I seem to be hitting this problem](https://github.com/feltech/cucumber-cpp-runner/actions/runs/6128296499/job/16635157800)(?) with clang on an ubuntu-20 runner with `aminya/setup-cpp@v0.35.3` .  I.e. in the workflow log I see

```
  env:
<snip>
    LDFLAGS: -L\"/usr/lib/llvm-13/lib\"
    CPPFLAGS: -I\"/usr/lib/llvm-13/include\"
<lots of snip>
 ./libtool: line 5195: cd: "/usr/lib/llvm-13/lib": No such file or directory
libtool: link: cannot determine absolute directory name of `"/usr/lib/llvm-13/lib"'
```

Is this a separate issue? or am I missing something?

In case its useful, this is a `conan` install of `boost` which is trying to build its dependency `libbacktrace` when it fails.

**Comment by aminya** [comment]
I fixed the quotation issues previously. Could you check if the directory exists?
You can edit the .cpprc to test different combinations that potentially work.
