### ISSUE TITLE
add llvm 18 support

### ISSUE THREAD

**Issue by tchaikov** [aminya/setup-cpp#228]
since llvm 18 is around the corner, can we add support for it? i will create a pull request for this if this is acceptable. it would be great if we can even support llvm 19. as, under some circumstances, we need to test the compatibility of a library to see if it is compatible with the latest clang. i would be happy to create a pull request for this as well.

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/228">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/228/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/228/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
We should wait for the release
https://github.com/llvm/llvm-project/releases

**Comment by aminya** [comment]
@tchaikov would you want to make a PR?
