### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by lczech** [aminya/setup-cpp#231]
Hi there,

thank you for making and maintaining this Action! 

It seems that GitHub started warning about Node.js deprecation. All my jobs display the following warning on their main workflow run page:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: aminya/setup-cpp@v0.36.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

This is with the latest release of setup-cpp.

Hope that helps, cheers and so long
Lucas

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/231">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/231/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/231/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
Hi @lczech, thanks for letting me know. #232 should fix this.
