### ISSUE TITLE
Fail to download LLVM from llvm.org

### ISSUE THREAD

**Issue by bjosv** [aminya/setup-cpp#295]
When setup-cpp v0.41.0 attempts to download a release from llvm.org it fails due to URL redirections.

```
  Installing llvm 5 x64 via direct downloading
  Downloading LLVM from https://llvm.org/releases/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  Download llvm 5
  Trying https://llvm.org/releases/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz #1 at 3:12:25 PM
  Redirect from HTTPS to HTTP protocol. This downgrade is not allowed for security reasons. If you want to allow this behavior, set the allowRedirectDowngrade option to true.
  Waiting 16 seconds before trying again
  Redirect from HTTPS to HTTP protocol. This downgrade is not allowed for security reasons. If you want to allow this behavior, set the allowRedirectDowngrade option to true.
  Waiting 18 seconds before trying again
  Error: Redirect from HTTPS to HTTP protocol. This downgrade is not allowed for security reasons. If you want to allow this behavior, set the allowRedirectDowngrade option to true.
  ```
The address: `https://llvm.org/releases/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz`
gives a (problematic) location: `http://releases.llvm.org/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz`
which gives the final location: `https://releases.llvm.org/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz`

Should we use `https://releases.llvm.org/${websiteAsset.tag}/${websiteAsset.name}` in [llvm_url.ts](https://github.com/aminya/setup-cpp/blob/d7f5466d9291418bde1d5f5a702ad895f9890b34/src/llvm/llvm_url.ts#L74) until the root cause is fixed? I don't know if this is a temporary or a lasting issue with llvm.org.

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/295">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/295/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/295/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
The solution is to pass `allowRedirectDowngrade` to `HttpClient`, so that it downgrades HTTPS to HTTP
https://github.com/actions/toolkit/blob/6dd369c0e648ed58d0ead326cf2426906ea86401/packages/http-client/src/index.ts#L164

However, that option is not exposed in `downloadTool`, which is what we're using for downloading binaries.
https://github.com/aminya/setup-cpp/blob/d7f5466d9291418bde1d5f5a702ad895f9890b34/src/utils/setup/setupBin.ts#L142

So, I might have to patch `@actions/tool-cache`.
https://github.com/aminya/setup-cpp/tree/master/patches

**Comment by aminya** [comment]
Also, it seems all URLs are redirected to `release.llvm.org`, so it might be just easier to change the URL.
Do you want to try a pull request? @bjosv

**Comment by bjosv** [comment]
Thanks! I wasn’t quick enough, but next time 😀

**Comment by aminya** [comment]
You're welcome
