### ISSUE TITLE
Support Arch-based Linux for apt installed packages

### ISSUE THREAD

**Issue by aminya** [aminya/setup-cpp#31]
Currently, some of the packages like gcc are installed using apt on Linux. We can add support for Arch-based systems by either 
- downloading binaries or packages directly 
- using `packman` instead.

Packages to support on Arch:
- [x] python
- [x] ccache
- [x] sevenzip
- [x] doxygen
- [x] make
- [x] cppcheck
- [x] vcpkg dependencies (curl, zip, unzip, tar, git, pkg-config)
- [x] llvm dependencies (ld, etc)

https://github.com/aminya/setup-cpp/search?p=1&q=setupAptPack

**Comment by abeimler** [comment]
`pacman` commands:

* basics (for vcpkg): `pacman -Sy curl pkg-config zip unzip tar git`
* python: `pacman -Sy python python-pip`
* ccache: `pacman -Sy ccache`
* sevenzip: `pacman -Sy p7zip`
* doxygen: `pacman -Sy doxygen`
* make: `pacman -Sy make`
* ninja: `pacman -Sy ninja`
* cppcheck: `pacman -Sy cppcheck`
* clang: `pacman -Sy clang`
* llvm: `pacman -Sy clang llvm`

**Comment by aminya** [comment]
We need to write a `setupPackmanPack`  function. 
https://github.com/aminya/setup-cpp/blob/master/src/utils/setup/setupAptPack.ts

**Comment by aminya** [comment]
Fixed by #95
