### ISSUE TITLE
Docker: clean up after setup

### ISSUE THREAD

**Issue by abeimler** [aminya/setup-cpp#59]
Hello,
I'm using setup-cpp in my Dockerfile and saw the generated Layer is big (when installing a lot of tools). 

## Problem

![image](https://user-images.githubusercontent.com/22779737/165318968-6a051c84-0209-422a-825e-455ce5054fdf.png)
16.3 GB

_(it's hard to upload something this big to docker hub)_

**Dockerfile**
```dockerfile
## base image
FROM ubuntu:latest as base

ARG extra_libraries

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y && apt-get install --no-install-recommends -y gnupg software-properties-common
# Install packages available from standard repos
RUN apt-get update -y && \
    apt-get install --no-install-recommends -yq \
        wget curl pkg-config zip unzip tar git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# add setup_cpp
RUN wget --no-verbose "https://github.com/aminya/setup-cpp/releases/download/v0.13.1/setup_cpp_linux"
RUN chmod +x ./setup_cpp_linux
RUN ./setup_cpp_linux --compiler llvm --cmake true --ninja true --ccache true --clangformat true --clangtidy true
```

I add `rm -rf /tmp/* && apt-get clean && rm -rf /var/lib/apt/lists/*` for clean up and got: 14.3 GB
```dockerfile
RUN ./setup_cpp_linux --compiler llvm \
    --cmake true --ninja true --ccache true \
    --cppcheck true --clangtidy true --clangformat true \
    --gcovr true --conan true --doxygen true && \
    rm -rf /tmp/* && apt-get clean && rm -rf /var/lib/apt/lists/*
```
_(cleaning up the /tmp-folder seem to a bit help ?)_

### Readme example

```dockerfile
RUN ./setup_cpp_linux --compiler llvm --cmake true --ninja true --ccache true --vcpkg true
```
![image](https://user-images.githubusercontent.com/22779737/165325638-b20a5d5d-e676-456d-8c34-665b41cb50a6.png)

### gcc + conan

```dockerfile
RUN ./setup_cpp_linux --compiler gcc --cmake true --ninja true --ccache true --conan true
```
**Layer Size: 303.4 MB**

### with clang tools

idk why but the clang-tools seems huge after setup.

```dockerfile
RUN ./setup_cpp_linux --compiler llvm --cmake true --ninja true --ccache true --conan true --cppcheck true --clangtidy true --clangformat true
```
**Layer Size: 16 GB**

#### with clangtidy

```dockerfile
RUN ./setup_cpp_linux --compiler llvm --cmake true --ninja true --ccache true --clangtidy true
```
**Layer Size: 11 GB**

#### with clangformat

```dockerfile
RUN ./setup_cpp_linux --compiler llvm --cmake true --ninja true --ccache true --clangformat true
```
**Layer Size: 11 GB**

### My old setup

```bash
apt-get install --no-install-recommends -yq 
          gcc wget curl pkg-config zip unzip tar git build-essential &&     
apt-get install --no-install-recommends -y
          clang binutils bison
          python3 python3-pip doxygen graphviz         
          cmake make ninja-build ccache cppcheck cmake-extras   
          clang-tidy clang-format    
          valgrind gcovr linux-tools-common linux-tools-generic google-perftools         
          neovim emacs nano &&     
apt-get clean && rm -rf /var/lib/apt/lists/*
```
My old version with only apt-get setup was 1.1 GB (Layer Size)

## Directory sizes in (docker) image

```dockerfile
RUN du -sh /root/cmake
RUN du -sh /root/ninja
RUN du -sh /root/clangtidy
RUN du -sh /root/clangformat
RUN du -sh /root/llvm
```

**Output**
```bash
141M    /root/cmake
224K    /root/ninja
4.4G    /root/clangtidy
4.4G    /root/clangformat
4.4G    /root/llvm
```

Seems like llvm, clangtidy and clangformat are the same.
when installing llvm, and clang-tools, `clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz` gets downloaded multiple times. (and extract into /root/llvm, /root/clang... ?)

**Comment by aminya** [comment]
We should use the same path for clang-tools. It seems that the caching system is not working for llvm that it re-installs it.

However, keep in mind that this image is a dev/build image. You should only use it for building once in your CI system. To run your app, use a distroless image. 
https://github.com/GoogleContainerTools/distroless
```
FROM ubuntu:devel as builder
# ... setup-cpp

# then build your app (e.g. using cmake)

FROM gcr.io/distroless/cc
COPY --from=builder /build/your_binary /
COPY --from=builder /build/your_dll_files /
CMD ["./your_binary"]
```

**Comment by aminya** [comment]
In the meantime, remove `--clangtidy` and `--clangtools`.

**Comment by abeimler** [comment]
>  We should use the same path for clang-tools. 
Yes I agree, `--clangtindy` and --clangformat` are basically aliases for llvm, clang-tidy is already included in llvm.

**Comment by aminya** [comment]
0.13.2 is released that fixes this issue
