### ISSUE TITLE
Clangtidy true is preferred over llvm-13.0.0

### ISSUE THREAD

**Issue by lefticus** [aminya/setup-cpp#64]
Version 13.0.0 is specifically requested here:

https://github.com/cpp-best-practices/gui_starter_template/blob/main/.github/workflows/ci.yml#L37

And we can see the attempted install here:

https://github.com/cpp-best-practices/gui_starter_template/runs/6197967250?check_suite_focus=true#step:4:221

But clang 14.0.0 is found:

https://github.com/cpp-best-practices/gui_starter_template/runs/6197967250?check_suite_focus=true#step:6:17

**Comment by aminya** [comment]
Since `clangtidy` is installed before llvm, it is used as the cache. So, if you pass 13.0.0 to all the llvm tools, the issue will be fixed.

However, I am planning to revert to llvm 13.0.0 as the default because of #53

**Comment by aminya** [comment]
The default llvm is now 13.0.0
#65
