### ISSUE TITLE
Windows usage example fails in Windows 10

### ISSUE THREAD

**Issue by Wihmajster** [aminya/setup-cpp#72]
Example usage for windows works neither in PowerShell nor in command prompt (tested in Windows 10 sandbox).
```ps1
curl -LJO "https://github.com/aminya/setup-cpp/releases/download/v0.14.0/setup_cpp_windows.exe"
```
That works in command prompt. However, it fails in PowerShell. Curl is an alias for Invoke-WebRequest in PowerShell. Replacing curl with curl.exe should work:
```ps1
curl.exe -LJO "https://github.com/aminya/setup-cpp/releases/download/v0.14.0/setup_cpp_windows.exe"
```

---

```ps1
./setup_cpp_windows --compiler llvm --cmake true --ninja true --ccache true --vcpkg true
```
That works in PowerShell but fails in the command prompt. Replacing Forward Slash with Backslash should work:
```ps1
.\setup_cpp_windows --compiler llvm --cmake true --ninja true --ccache true --vcpkg true
```

---

Moreover, `RefreshEnv.cmd` fails If chocolatey has just been installed by setup_cpp. I am not sure what is the best solution in this case. 
```ps1
\ProgramData\chocolatey\bin\RefreshEnv.cmd
```
The above command works unless you have changed chocolatey default install location. However, both fails when you don't have choco installed, and setup_cpp does not install it either.

**Comment by aminya** [comment]
Thanks for letting me know! Do you want to make a pull request fixing the readme? 

For `refreshenv`, I can add a short note.
