### ISSUE TITLE
gcovr new version broke build.

### ISSUE THREAD

**Issue by ArthurSonzogni** [aminya/setup-cpp#86]
This patch:
https://github.com/aminya/setup-cpp/commit/0188a5abb2cd101f815c18b680ff41fa10536fe9
increase gcovr version from 5.0 toward 5.1

Version 5.1 contained a bug. See:
https://github.com/gcovr/gcovr/issues/620#issuecomment-1128440130

It caused errors on my workflow:
https://github.com/ArthurSonzogni/FTXUI/pull/405/checks

What about reverting version toward the last known working one?

**Comment by aminya** [comment]
Oh. It had a bug on gcovr 5.0 too. The Jinja library was not installed properly. Not sure what to do. 

You can pass "5.0" instead of "true" in the meantime.

**Comment by ArthurSonzogni** [comment]
Thanks!
I didn't know I can specify the version myself. Great! This fixes my issue.
